# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    twig:
        mode: lazy

    filter_sets:
        # Filtre pour afficher les photos de profil dans les commentaires
        profil:
            quality: 75
            filters:
                scale:
                    dim: [700, 700]

        comment:
            quality: 75
            filters:
                scale:
                     dim: [100, 100]


